### ISSUE TITLE
Create data question about belonging and transit

### ISSUE THREAD

**Issue by vingkan** [scarletstudio/transithealth#106]
**Data Question Topic:** How does community belonging relate to transit?

(We are still brainstorming.)

Write a one-sentence description here for what your data question will help visitors learn about.

[Fabian's Brainstorming Document](https://docs.google.com/document/d/1AzZsK7DlHaPW4KRCYpp68VAl8pCs3avjnWkyyPSgQNU/edit?usp=sharing)

## Resources

Questions to think about:

- Why do visitors want to know about this topic?
- What are some limitations of the data to keep in mind?
- What views do you want to use to present the data? (Visualizations, tables, text, videos, audio?)
- Is additional work on the backend API and offline pipeline necessary to support this question?

Read the documentation on how to add a new data question:

- [Short Guide](https://github.com/scarletstudio/transithealth/blob/main/docs/pages/tasks.md#add-a-component)
- [Full Guide](https://github.com/scarletstudio/transithealth/blob/main/docs/pages/new_question.md)

## Task List

This task is more open-ended and will involve two or more pull requests:

### Sub-Question 1

- [ ] Offline pipeline work
- [ ] Backend API work
- [ ] Frontend app work

### Sub-Question 1

- [ ] Offline pipeline work
- [ ] Backend API work
- [ ] Frontend app work

### Data Question

- [ ] Create a practice data visualization
- [ ] Create initial question page (add site entry and component)
- [ ] Launch your question page!
